name: "Vprofile IAC"

on:
  push:
    branches:
      - "main"
      - "stage"
    paths:
      - 'terraform/**'
  pull_request:
    branches:
      - "main"
    paths:
      - 'terraform/**'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_TF_SECRET: ${{ secrets.BUCKET_TF_SECRET }}
  AWS_REGION: "us-west-1"
  EKS_CLUSTER: "VPROFILE-eks"

jobs:
  terraform:
    name: "Apply Terraform code changes"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=$BUCKET_TF_SECRET"

      - name: Apply Terraform format
        id: fmt
        run: terraform fmt -check

      - name: Apply Terraform validate
        id: validate
        run: terraform validate

      - name: Apply Terraform plan
        id: plan
        run: terraform plan -no-color -input=false -out=planfile

      - name: Apply Terraform
        id: apply
        run: terraform apply -input=false planfile
        continue-on-error: true

      - name: Plan status
        if: ${{ failure() }}
        run: exit 1
